stages:
  - test
  - doc
  - code_quality
  - build
  - deploy

variables:
  COVERAGE_TYPE: "Dymola"
  PAGES_BRANCH: master
  PYTHON_VERSION: "python:3.9"
  TEST_ENGINE: "unittest"

include:
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'python/code-quality/pylint.gitlab-ci.yml'
    ref: '33-remove-images'
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'python/doc/sphinxdoc.gitlab-ci.yml'
    ref: '33-remove-images'
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'python/build/build.gitlab-ci.yml'
    ref: '33-remove-images'
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'pages/pages.gitlab-ci.yml'
    ref: '33-remove-images'
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'python/tests/tests.gitlab-ci.yml'
    ref: '33-remove-images'
  - project: 'EBC/EBC_all/gitlab_ci/templates'
    file: 'python/tests/coverage.gitlab-ci.yml'
    ref: '33-remove-images'
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
